package main

import (
	"encoding/json"
	"fmt"
	"os"
)

type JsonObject map[string]interface{}

// JSON正本からブラウザ用JSを生成する。
func main(){
	generate(
		"data/items.json",
		"items.generated.js",
		"// Generated from data/items.json. Do not edit this file directly.\nconst ITEM_DATA=",
		";\nconst ITEMS=ITEM_DATA.items.map(x=>({id:x.id,domain:x.domain,domainJa:x.domain_ja,facet:x.facet,facetJa:x.facet_ja,key:x.key,en:x.original,ja:x.translation,note:x.guidance}));\n",
	)
	generate(
		"data/review-groups.json",
		"review-groups.generated.js",
		"// Generated from data/review-groups.json. Do not edit this file directly.\nconst REVIEW_GROUP_DATA=",
		";\nconst SIMILAR_GROUPS=REVIEW_GROUP_DATA.groups;\n",
	)
}

// JSONを読み込み、指定したJS定数として出力する。
func generate(inputPath, outputPath, prefix, suffix string){
	b, err := os.ReadFile(inputPath)
	if err != nil { panic(err) }
	var v JsonObject
	if err := json.Unmarshal(b, &v); err != nil { panic(err) }
	compact, err := json.Marshal(v)
	if err != nil { panic(err) }
	out := append([]byte(prefix), compact...)
	out = append(out, []byte(suffix)...)
	if err := os.WriteFile(outputPath, out, 0644); err != nil { panic(err) }
	fmt.Println("generated " + outputPath)
}
