package main

import (
	"encoding/json"
	"fmt"
	"os"
)

type ItemData map[string]interface{}

func main(){
	b, err := os.ReadFile("data/items.json")
	if err != nil { panic(err) }
	var v ItemData
	if err := json.Unmarshal(b, &v); err != nil { panic(err) }
	compact, err := json.Marshal(v)
	if err != nil { panic(err) }
	out := append([]byte("// Generated from data/items.json. Do not edit this file directly.\nconst ITEM_DATA="), compact...)
	out = append(out, []byte(";\nconst ITEMS=ITEM_DATA.items.map(x=>({id:x.id,domain:x.domain,domainJa:x.domain_ja,facet:x.facet,facetJa:x.facet_ja,key:x.key,en:x.original,ja:x.translation,note:x.guidance}));\n")...)
	if err := os.WriteFile("items.generated.js", out, 0644); err != nil { panic(err) }
	fmt.Println("generated items.generated.js")
}
